### PR TITLE
Add support for caching the Whois entries into Redis

### PR DESCRIPTION
**Pull request by Rafiot**

### CODE REVIEW

**Comment by Rafiot** [comment]
Any news on the plugin system? I already diverged quite a bit from your code base and would like to get somewhat closer.

**Comment by kgaughan** [comment]
Finally got around to writing the plugin system, though it needs to be documented.

I'll also be writing something similar for rate limiting this evening, I hope.

If you want to see how to register plugins, see `setup.py` and `uwhoisd.caching`. Other than that, the config file's `[cache]` section gets a new option called `type`, which is a callable (so either a function or a class will work just fine) that returns a cache implementation. The cache receives the other fields in `[cache]` as keyword arguments. `uwhoisd.caching.LFU` demonstrates the interface: a cache needs to implement all the methods it does.

**Comment by Rafiot** [comment]
I need to get my head around it, and see how/if I can make useful pull requests: I realized that I changed quite some of the logic in the way the servers are queried, removed a good of chunk of code I wasn't using (all the caching part), and added a whowas functionality.

**Comment by kgaughan** [comment]
Thankfully, it's not too complicated: I could write a dummy cache plugin as an example, if it'd help? I'm going to be doing that as part of the documentation anyway and it'd just mean doing it a bit sooner that I'd intended.

I have to take a look at how the whowas functionality is implemented. While I'm a little iffy on building functionality like that directly into uwhoisd myself, I'd like it to at least be possible for it to be added as a plugin of some sort.

Some of the config changes look worth porting over, so it might be useful plucking them out into a separate branch.

I noticed one thing in the Tornado rewrite that might need changing: the internal WHOIS client is synchronous rather than using `tornado.tcpclient.TCPClient`. One of the issue uwhoisd has to deal with at my work is slow/unresponsive registrar WHOIS servers, so having queries to such servers not block is very useful.

**Comment by kgaughan** [comment]
I did some work on simplifying the plugin interface and put together a version of a Redis cache plugin inspired by your code: https://github.com/kgaughan/uwhoisd-redis-cache

I haven't tested everything yet, but I thought you might be interested in taking a look.

It's a good example cache for anybody who might want to implement another cache in the future.

**Comment by Rafiot** [comment]
Looks great, I will try to dig into the changes today and get my fork in line with your code base

**Comment by Rafiot** [comment]
That's good, your approach is definitely cleaner than mine.

**Pull request closed without merging**
