### PR TITLE
Initial support of IP Whois querying

### PR DESCRIPTION
**Pull request by Rafiot**
This is a first draft.

TODO: IPv6 Support, cleaner handling of the prefix....

Just let me know please if you want to merge it upstream in the future or not.

### CODE REVIEW

**Comment by Rafiot** [comment]
Any news on that part?

**Comment by Rafiot** [comment]
https://github.com/Rafiot/uwhoisd/blob/testing/uwhoisd/net.py <= initial portage to tornado instead of diesel (also support python3)

**Comment by Rafiot** [comment]
I use the tornado backend in production now. Please let me know if you want me to do a clean pull request.

**Comment by kgaughan** [comment]
Sorry for not replying sooner. I'll take a look at the patch this evening when I get a chance.

**Comment by Rafiot** [comment]
No problem.

The Tornado code isn't production ready (seems to hang sometimes for no obvious reason).

**Comment by Rafiot** [comment]
Now that tornado is there, should I re-do a clean PR for the IP whois? (as in are you interested in merging it, or not)

**Comment by kgaughan** [comment]
I've a branch called kgaughan/scraper-factoring that includes code for pulling down the IPv4 assignments, but doesn't do anything more with them other than print them out.

This version uses the XML file, because the CSV file doesn't look to contain clean lists of RDAP servers, and at some point uwhoisd might support RDAP in some form.

You might want to take a quick look over it.

**Comment by Rafiot** [comment]
Sure, I'll look at it, thank you very much

**Comment by Rafiot** [comment]
I looked a bit at the assignations and I think we should use IPy (python 2.x) and ipaddress (python3): we will not be able to use the same trick for ipv6 as for ipv4 (1st number of the IP): https://www.iana.org/assignments/ipv6-unicast-address-assignments/ipv6-unicast-address-assignments.xhtml <- the size of the block varies.

So we should store the full block in the config file, load it in memory when ushois d starts and lookup through it to find the server to query when a user passes an IP instead of a domain.

**Pull request closed without merging**
